# Generated by Django 5.2.4 on 2025-07-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPinterest', '0002_savedpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=5)),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='myPinterest.pin')),
            ],
        ),
    ]
