# Generated by Django 5.2.4 on 2025-07-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPinterest', '0004_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes_count',
        ),
    ]
